apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bodybuddy
  namespace: bodybuddy-system
spec:
  description: BodyBuddy application workloads
  sourceRepos:
    - https://github.com/dongjune8931/bdbd.git
  destinations:
    - namespace: bodybuddy
      server: https://kubernetes.default.svc
    - namespace: bodybuddy-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
