apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bodybuddy
  namespace: bodybuddy-system
spec:
  description: BodyBuddy application workloads
  sourceRepos:
    - https://github.com/dongjune8931/bdbd.git
    - https://kedacore.github.io/charts
    - https://prometheus-community.github.io/helm-charts
    - https://kubecost.github.io/cost-analyzer/
    - https://kubernetes-sigs.github.io/metrics-server/
  destinations:
    - namespace: bodybuddy
      server: https://kubernetes.default.svc
    - namespace: bodybuddy-system
      server: https://kubernetes.default.svc
    - namespace: kubecost
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: keda
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
