apiVersion: v1
kind: ConfigMap
metadata:
  name: bodybuddy-grafana-tempo-datasource
  namespace: bodybuddy-system
  labels:
    grafana_datasource: "1"
data:
  bodybuddy-tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.bodybuddy-system.svc.cluster.local:3100
        isDefault: false
        editable: false
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          tracesToLogsV2:
            datasourceUid: bodybuddy-cloudwatch
            tags:
              - key: service.name
                value: service
              - key: k8s.pod.name
                value: pod
          tracesToMetrics:
            datasourceUid: prometheus
            tags:
              - key: service.name
                value: service
          nodeGraph:
            enabled: true
