apiVersion: v1
kind: ConfigMap
metadata:
  name: bodybuddy-grafana-cloudwatch-datasource
  namespace: bodybuddy-system
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: bodybuddy
data:
  bodybuddy-cloudwatch-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: BodyBuddy CloudWatch
        uid: bodybuddy-cloudwatch
        type: cloudwatch
        access: proxy
        editable: true
        isDefault: false
        jsonData:
          authType: default
          defaultRegion: ap-northeast-2
