apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  role: bodybuddy-dev-eks-karpenter-node
  subnetSelectorTerms:
    - id: subnet-0b050f536f668ad59
    - id: subnet-0ccf4f8f199c2efde
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: bodybuddy-dev-eks
  tags:
    Project: bodybuddy
    Environment: dev
    ManagedBy: argocd
    karpenter.sh/discovery: bodybuddy-dev-eks
