apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  role: bodybuddy-dev-eks-karpenter-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: bodybuddy-dev-eks
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: bodybuddy-dev-eks
  tags:
    Environment: dev
    ManagedBy: argocd
    Project: bodybuddy
    karpenter.sh/discovery: bodybuddy-dev-eks
