{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "analysis-worker.fullname" . }}
  labels:
    {{- include "analysis-worker.labels" . | nindent 4 }}
spec:
  podIdentity:
    provider: aws-eks
{{- end }}
